# -*- coding: utf-8 -*-
"""project 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11YEyDv8NclloEA-q4xmUy1Q-PDkrGw2X
"""

import pandas as pd
import numpy as np

df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/accident_prediction_india.csv")

State_Name = df["State Name"].to_numpy()
print(State_Name)

city_name = df["City Name"].to_numpy()
print(city_name)

year = df["Year"].to_numpy()
print(year)

month = df["Month"].to_numpy()
print(month)

day_of_week = df["Day of Week"].to_numpy()
print(day_of_week)

time_of_day = df["Time of Day"].to_numpy()
print(time_of_day)

accident_severity = df["Accident Severity"].to_numpy()
print(accident_severity)

Number_of_vehicles_involved = df["Number of Vehicles Involved"].to_numpy()
print(Number_of_vehicles_involved)

number_of_casualties = df["Number of Casualties"].to_numpy()
print(number_of_casualties)

number_of_fatalities = df["Number of Fatalities"].to_numpy()
print(number_of_fatalities)

weather_conditions = df["Weather Conditions"].to_numpy()
print(weather_conditions)

road_type = df["Road Type"].to_numpy()
print(road_type)

road_condition = df["Road Condition"].to_numpy()
print(road_condition)

lighting_condition = df["Lighting Conditions"].to_numpy()
print(lighting_condition)

traffic_control_presence = df["Traffic Control Presence"].to_numpy()
print(traffic_control_presence)

speed_limit = df["Speed Limit (km/h)"].to_numpy()
print(speed_limit)

Driver_age = df["Driver Age"].to_numpy()
print(Driver_age)

Driver_Gender = df["Driver Gender"].to_numpy()
print(Driver_Gender)

Driver_license_status = df["Driver License Status"].to_numpy()
print(Driver_license_status)

Alcohol_involvement = df["Alcohol Involvement"].to_numpy()
print(Alcohol_involvement)

accident_location_Details= df["Accident Location Details"].to_numpy()
print(accident_location_Details)

weather_df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/accident_prediction_india.csv')
print("Historical weather data loaded successfully.")
print(weather_df.head())

try:
    weather_df = pd.read_csv('/content/drive/MyDrive/my_weather_data.csv')
    print("Historical weather data loaded successfully.")
    print(weather_df.head())
except FileNotFoundError:
    print("Error: The file 'my_weather_data.csv' was not found at '/content/drive/MyDrive/'. Please ensure the file is present in your Google Drive and mounted correctly.")
    weather_df = pd.DataFrame() # Create an empty DataFrame to avoid further errors
    print("An empty DataFrame named `weather_df` has been created to prevent subsequent errors.")

try:
    weather_df = pd.read_csv('/content/drive/MyDrive/my_weather_data.csv')
    print("Historical weather data loaded successfully.")
    print(weather_df.head())
except FileNotFoundError:
    print("Error: The file 'my_weather_data.csv' was not found at '/content/drive/MyDrive/'. Please ensure the file is present in your Google Drive and mounted correctly.")
    weather_df = pd.DataFrame() # Create an empty DataFrame to avoid further errors
    print("An empty DataFrame named `weather_df` has been created to prevent subsequent errors.")

try:
    weather_df = pd.read_csv('/content/drive/MyDrive/my_weather_data.csv')
    print("Historical weather data loaded successfully.")
    print(weather_df.head())
except FileNotFoundError:
    print("Error: The file 'my_weather_data.csv' was not found at '/content/drive/MyDrive/'. Please ensure the file is present in your Google Drive and mounted correctly.")
    weather_df = pd.DataFrame() # Create an empty DataFrame to avoid further errors
    print("An empty DataFrame named `weather_df` has been created to prevent subsequent errors.")

try:
    weather_df = pd.read_csv('/content/drive/MyDrive/my_weather_data.csv')
    print("Historical weather data loaded successfully.")
    print(weather_df.head())
except FileNotFoundError:
    print("Error: The file 'my_weather_data.csv' was not found at '/content/drive/MyDrive/'. Please ensure the file is present in your Google Drive and mounted correctly.")
    weather_df = pd.DataFrame() # Create an empty DataFrame to avoid further errors
    print("An empty DataFrame named `weather_df` has been created to prevent subsequent errors.")

print("Shape of weather_df:", weather_df.shape)
print("\nInfo of weather_df:")
weather_df.info()
print("\nHead of weather_df:")
print(weather_df.head())
print("\nMissing values in weather_df:")
print(weather_df.isnull().sum())

print("\nDescriptive statistics for numerical columns:")
print(weather_df.describe())

print("\nUnique values and counts for categorical columns:")
for column in weather_df.select_dtypes(include=['object', 'category']).columns:
    print(f"\nColumn: {column}")
    print("Unique Values:", weather_df[column].unique())
    print("Value Counts:\n", weather_df[column].value_counts())

if weather_df.empty:
    print("weather_df is empty. Cannot generate descriptive statistics or categorical column analysis.")
else:
    print("\nDescriptive statistics for numerical columns:")
    print(weather_df.describe())

    print("\nUnique values and counts for categorical columns:")
    for column in weather_df.select_dtypes(include=['object', 'category']).columns:
        print(f"\nColumn: {column}")
        print("Unique Values:", weather_df[column].unique())
        print("Value Counts:\n", weather_df[column].value_counts())

import matplotlib.pyplot as plt
import seaborn as sns

if weather_df.empty:
    print("weather_df is empty. Cannot generate a histogram for temperature distribution.")
else:
    # Assuming 'Temperature' column exists if weather_df was not empty
    if 'Temperature' in weather_df.columns:
        plt.figure(figsize=(10, 6))
        sns.histplot(weather_df['Temperature'], kde=True)
        plt.title('Distribution of Temperature Values')
        plt.xlabel('Temperature')
        plt.ylabel('Frequency')
        plt.grid(True)
        plt.show()
    else:
        print("The 'Temperature' column is not found in weather_df.")

import matplotlib.pyplot as plt
import seaborn as sns

if weather_df.empty:
    print("weather_df is empty. Cannot generate a scatter plot for Temperature vs. Humidity.")
else:
    if 'Temperature' in weather_df.columns and 'Humidity' in weather_df.columns:
        plt.figure(figsize=(10, 6))
        sns.scatterplot(x=weather_df['Temperature'], y=weather_df['Humidity'])
        plt.title('Temperature vs. Humidity Relationship')
        plt.xlabel('Temperature')
        plt.ylabel('Humidity')
        plt.grid(True)
        plt.show()
    else:
        missing_cols = []
        if 'Temperature' not in weather_df.columns:
            missing_cols.append('Temperature')
        if 'Humidity' not in weather_df.columns:
            missing_cols.append('Humidity')
        print(f"The following required column(s) were not found in weather_df: {', '.join(missing_cols)}.")

import matplotlib.pyplot as plt
import seaborn as sns

if weather_df.empty:
    print("weather_df is empty. Cannot generate a pie chart for seasonal weather distribution.")
else:
    if 'Season' in weather_df.columns:
        seasonal_counts = weather_df['Season'].value_counts()
        plt.figure(figsize=(8, 8))
        plt.pie(seasonal_counts, labels=seasonal_counts.index, autopct='%1.1f%%', startangle=140)
        plt.title('Seasonal Weather Distribution')
        plt.axis('equal') # Equal aspect ratio ensures that pie is drawn as a circle.
        plt.legend(title="Seasons")
        plt.show()
    else:
        print("The 'Season' column is not found in weather_df. Please ensure seasons are derived from date columns first.")